basic_settings:
  site_title: Nick McClellan.com
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
#    - title: 'Projects'
#      url: '/'
#    - title: 'Blog'
#      url: '/blog/'
#    - title: 'About'
#      url: '/about'
#    - title: 'Contact'
#      url: '/contact'

footer_settings:
  footer_tagline: Fasten your seat belts. It's going to be a bumpy night.

hero_settings:
  overlay_opacity: 0.8

post_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  linkedin_url: 'https://www.linkedin.com/in/nick-mcclellan-21b27517'
  instagram_url: 'https://www.instagram.com/nickmcclellan/'
  threads_url: 'https://www.threads.net/@nickmcclellan'
  facebook_url: 'https://facebook.com/nick.mcclellan/'
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/user/basuraboi3'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://medium.com/@nickmcclellan/'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  x-twitter_url: 'https://twitter.com/nickmcclellan/'

color_settings:
  background_color: '#000'
  inverse_background_color: '#FFF'
  background_alt_color: '#A1F2CC'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#F2A0C6'
  accent_color: '#A3A1F2'
  border_color: '#dddddd'
  hero_background_color: '#132930'
  hero_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Raleway:200,300,500,600" rel="stylesheet">'
  title_font: '"Raleway", sans-serif;'
  body_font: '"Raleway", sans-serif;'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    small_size: 35
    medium_size: 45
    large_size: 60
    weight: 700
    letter_spacing: -0.03
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 18
    medium_size: 20
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: "<!-- Google tag (gtag.js) --><script async src='https://www.googletagmanager.com/gtag/js?id=G-MRM614KD0S'></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'G-MRM614KD0S');</script>"
  custom_styles: ""
  header_js: ""
  footer_js: ""
