<?php
// $Id: disqus.install,v 1.1.2.4.2.2 2010/03/19 11:02:54 robloach Exp $

/**
 * @file
 * Provides any required installation or upgrade path requirements.
 */

/**
 * Implements hook_uninstall().
 */
function disqus_uninstall() {
  // Remove all Disqus-related variables.
  db_delete('variable')->condition('name', 'disqus_%', 'LIKE')->execute();
}

/**
 * Updates from Drupal 6 to 7.
 */
function disqus_update_7000() {
  // Nothing.
}
